# Generated by Django 5.2 on 2025-04-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_config_bonus_to_new_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='telegram_admins_id',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='config',
            name='telegram_bot_apikey',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='config',
            name='telegram_group_id',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='config',
            name='telegram_group_joined_promocode_token_amount',
            field=models.IntegerField(default=100000),
        ),
    ]
