"""
Django settings for source project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
import httpx
from openai import OpenAI
from pathlib import Path
from decouple import AutoConfig
from yandex_cloud_ml_sdk import YCloudML

BASE_DIR = Path(__file__).parent.parent.parent.parent

config = AutoConfig()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# BASE_URL = 'https://slideeeeeee.ru'
BASE_URL = 'https://slideee.ru'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m-!$bp7@^cd7@5ng3!2(he(%rx!s@-2t4zel+xue6=3cnx+p(m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOWED_ORIGINS = [
    'https://slideee.ru',
    'http://127.0.0.1:5173',
    'http://localhost:8001',
    'http://localhost:5173'
]

CSRF_TRUSTED_ORIGINS = [
    'https://slideee.ru',
    'http://localhost:8001',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'rest_framework',
    'presentation',
    'corsheaders',
    'main.apps.MainConfig',
    'telegram_bot.apps.TelegramBotConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Это должно быть выше
    'django.middleware.csrf.CsrfViewMiddleware',  # Это должно быть ниже
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'source.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'source.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('DJANGO_DATABASE_HOST'),
        'PORT': config('DJANGO_DATABASE_PORT', cast=int),
        'CONN_MAX_AGE': config('CONN_MAX_AGE', cast=int, default=60),
        'OPTIONS': {
            # 'pool': True,
            'connect_timeout': 10,
            'options': '-c statement_timeout=15000ms',
            # consider using 'isolation_level' set to 'serializable'
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'request-reset-password': '5/minute',
        'enter-request-reset-password': '10/minute',
    }
}

AUTH_USER_MODEL = 'presentation.User'


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'static'
STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "TOKEN_OBTAIN_SERIALIZER": "presentation.serializers.CustomTokenObtainPairSerializer",
}

OPENAI_CLIENT = OpenAI(
    api_key=config("OPENAI_CLIENT_API_KEY"),
    base_url="https://api.deepseek.com",
    # http_client=httpx.Client(proxy='http://109.248.32.81:3128')
)

OPENAI_IMAGE_CLIENT = OpenAI(
    api_key=config("OPENAI_IMAGE_CLIENT_API_KEY"),
    http_client=httpx.Client(proxy=config("OPENAI_IMAGE_CLIENT_PROXY")),
    timeout=110,
)

YANDEX_SDK = YCloudML(
    folder_id=config("YANDEX_SDK_FOLDER_ID"),
    auth=config("YANDEX_SDK_AUTH"),
)

PAYKEEPER_USER = config("PAYKEEPER_USER")
PAYKEEPER_PASSWORD = config("PAYKEEPER_PASSWORD")
PAYKEEPER_POST_SECRET_WORD = config("PAYKEEPER_POST_SECRET_WORD")
SERVER_PAYKEEPER = config("SERVER_PAYKEEPER")

# SMTP настройки в settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'sm20.hosting.reg.ru'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'registration@slideee.ru'
EMAIL_HOST_PASSWORD = 'registration@SLIDEmail'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

EMAIL_TEMPLATE_CACHE = {
    "verification_email": None,
    "reset_password_email": None,
}

FRONTEND_URL = "https://slideee.ru"

