# Generated by Django 5.0 on 2023-12-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_name', models.TextField()),
                ('source', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
