# Generated by Django 5.2 on 2025-07-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='group',
            field=models.CharField(choices=[('learn', 'Для учебы'), ('work_personal', 'Для Работы/Для личного использования')], default='learn', max_length=55),
        ),
    ]
