# Generated by Django 5.0 on 2023-12-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='source',
            field=models.ImageField(default=None, null=True, upload_to='pictures'),
        ),
    ]
