# Generated by Django 5.2.3 on 2025-11-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_user_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='token_price',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='presentation_count',
        ),
        migrations.AddField(
            model_name='scope',
            name='code',
            field=models.SlugField(default='default_scope_code', unique=True),
        ),
        migrations.AddField(
            model_name='scope',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='balancehistory',
            name='change_reason',
            field=models.CharField(choices=[('SP', 'Оплата генерации слайдов'), ('TGP', 'Оплата Генерации текста'), ('IGP', 'Оплата Генерации изображения'), ('TU', 'Пополнение'), ('BT', 'Бонус за пополнение'), ('BNU', 'Бонус за регистрацию'), ('RT', 'Реферальный бонус'), ('PC', 'Промокод'), ('AB', 'Бонус за активность')], help_text='Причина изменения баланса', max_length=3),
        ),
        migrations.AlterField(
            model_name='scope',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scope',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
