# Generated by Django 5.2.3 on 2025-11-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_change_tarrif_and_scope_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='tokens_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scope',
            name='code',
            field=models.SlugField(default='default_scope_code', max_length=64, unique=True),
        ),
    ]
