# Generated by Django 5.2.3 on 2025-12-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_add_amount_to_tariff_and_maxLength_to_scope_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='visible_in_advantages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='extra_text',
            field=models.TextField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='max_imgs_gen_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='max_slides_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='max_text_gen_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='one_token_cost',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
