# Generated by Django 5.2.3 on 2026-05-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0006_tariff_and_scope_modifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='theme',
            field=models.CharField(max_length=2048),
        ),
    ]
