# Generated by Django 5.1.2 on 2024-10-18 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0007_generatedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('CR', 'created'), ('CS', 'card_search'), ('WP', 'waiting_payment'), ('RT', 'rejected_timeout'), ('RO', 'reject_by_office'), ('RC', 'reject_manual_by_client'), ('PR', 'proceedings'), ('PN', 'proceedingsN'), ('CM', 'completed'), ('RS', 'rejected_by_system'), ('RD', 'rejected_by_new_deal')], help_text='Статусы', max_length=3)),
                ('payment_url', models.URLField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
