# Generated by Django 5.2.3 on 2026-05-23 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0007_increase_generated_image_theme_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='error_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='generated_images/'),
        ),
    ]
