# Generated by Django 5.1.2 on 2024-10-18 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0008_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
