# Generated by Django 5.1.2 on 2024-10-19 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0010_tariff_presentation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presentation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
