# Generated by Django 5.1.2 on 2025-01-27 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


def clear_user_balance(apps, schema_editor):
    User = apps.get_model('presentation', 'User')
    User.objects.update(balance=None)


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0011_user_presentation_alter_presentation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=90, max_digits=10)),
                ('next_payment_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'balance',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.RunPython(clear_user_balance, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_balance', to='presentation.balance'),
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи истории баланса (UUID)', primary_key=True, serialize=False)),
                ('amount_change', models.DecimalField(decimal_places=2, help_text='Изменение суммы на балансе', max_digits=10)),
                ('change_type', models.CharField(choices=[('Incr', 'Increase'), ('Decr', 'Decrease')], help_text='Тип изменения (увеличение/уменьшение)', max_length=4)),
                ('change_reason', models.CharField(choices=[('SP', 'Оплата Генерации слайдов'), ('TU', 'Пополнение'), ('BT', 'Бонус за пополнение'), ('RT', 'Реферальный бонус'), ('PC', 'Промокод'), ('AB', 'Бонус за активность')], help_text='Причина изменения баланса', max_length=3)),
                ('balance', models.ForeignKey(help_text='Связь с объектом баланса', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='presentation.balance')),
            ],
            options={
                'db_table': 'balance_history',
                'indexes': [models.Index(fields=['created_at', 'change_type', 'change_reason'], name='balance_history_index')],
            },
        ),
    ]
