# Generated by Django 5.1.2 on 2025-01-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0012_balance_alter_user_balance_balancehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('usage_type', models.CharField(choices=[('single', 'Одноразовый'), ('multi', 'Многоразовый')], max_length=10)),
                ('usage_limit', models.PositiveIntegerField(default=1)),
                ('expiration_date', models.DateField()),
                ('can_sum', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
