# Generated by Django 5.1.2 on 2025-01-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0014_promocodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='token_amount',
            field=models.IntegerField(default=0),
        ),
    ]
