# Generated by Django 5.1.6 on 2025-03-02 18:53

import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    Presentation = apps.get_model('presentation', 'Presentation')
    for presentation in Presentation.objects.all():
        presentation.share_link_uid = uuid.uuid4()
        presentation.save(update_fields=['share_link_uid'])


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0015_promocode_token_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='share_link_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),
    ]
