# Generated by Django 5.1.6 on 2025-03-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0017_user_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='change_reason',
            field=models.CharField(choices=[('SP', 'Оплата Генерации слайдов'), ('TU', 'Пополнение'), ('BT', 'Бонус за пополнение'), ('BNU', 'Бонус за регистрацию'), ('RT', 'Реферальный бонус'), ('PC', 'Промокод'), ('AB', 'Бонус за активность')], help_text='Причина изменения баланса', max_length=3),
        ),
    ]
