# Generated by Django 5.1.6 on 2025-03-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0020_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_thumb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
