# Generated by Django 5.2 on 2025-05-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0022_scope_tariff_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(default=[], to='presentation.roles'),
        ),
    ]
